server:
  port: 8050

spring:
  profiles:
    active: @spring.profiles.active@



knife4j:
  enableAggregation: true
  basicAuth:
    enable: true
    username: admin
    password: crcmcloud@123
  route-auth:
    enable: true
    username: admin
    password: crcmcloud@123
  nacos:
    enable: true  # 开启Nacos模式
    serviceUrl: http://localhost:8848/nacos # Nacos注册中心地址
    routes:
      - name: 默认文档
        service-name: aaa
        location: http://localhost:${server.port}/defaultApi.json
      - name: 后台管理服务  # 微服务在聚合文档中的名称
        serviceName: crcm-cloud-service-admin  # 微服务在Nacos注册中心的名称
        location: /v2/api-docs # 微服务文档资源路径
        namespace-id: ${spring.profiles.active}
#        servicePath: /api/app1 # 给每个接口添加路径前缀，作用是拼接出经过nginx和gateway处理前的实际接口url
      - name: 统一认证服务  # 微服务在聚合文档中的名称
        serviceName: crcm-cloud-service-auth  # 微服务在Nacos注册中心的名称
        location: /v2/api-docs # 微服务文档资源路径
        namespace-id: ${spring.profiles.active}
      - name: 文件存储服务服务  # 微服务在聚合文档中的名称
        serviceName: crcm-cloud-service-file  # 微服务在Nacos注册中心的名称
        location: /v2/api-docs # 微服务文档资源路径
        namespace-id: ${spring.profiles.active}
      - name: 智慧党建服务  # 微服务在聚合文档中的名称
        serviceName: crcm-cloud-business-partbuilding  # 微服务在Nacos注册中心的名称
        location: /v2/api-docs # 微服务文档资源路径
        namespace-id: ${spring.profiles.active}
      - name: 德育积分服务  # 微服务在聚合文档中的名称
        serviceName: crcm-cloud-business-education  # 微服务在Nacos注册中心的名称
        location: /v2/api-docs # 微服务文档资源路径
        namespace-id: ${spring.profiles.active}
      - name: 社会治理服务  # 微服务在聚合文档中的名称
        serviceName: crcm-cloud-business-governance  # 微服务在Nacos注册中心的名称
        location: /v2/api-docs # 微服务文档资源路径
        namespace-id: ${spring.profiles.active}
      - name: 考核评价服务  # 微服务在聚合文档中的名称
        serviceName: crcm-cloud-business-evaluations  # 微服务在Nacos注册中心的名称
        location: /v2/api-docs # 微服务文档资源路径
        namespace-id: ${spring.profiles.active}