server:
  port: 18858
  tomcat:
    max-http-form-post-size: 1000MB #请求参数长度
    max-swallow-size: 10MB

spring:
  application:
    name: @artifactId@
  messages:
    basename: "i18n/messages"
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://${MYSQL_HOST:10.150.1.13}:${MYSQL_PORT:3306}/${MYSQL_DB:sjz_develop}?useunicode=true&characterEncoding=utf-8&useTimezone=true&serverTimezone=Asia/Shanghai&allowPublicKeyRetrieval=true&verifyServerCertificate=false&useSSL=false&zeroDateTimeBehavior=convertToNull&allowMultiQueries=true&nullCatalogMeansCurrent=true&autoReconnect=true
    username:  ${MYSQL_USER:root}
    password: ${MYSQL_PWD:1234}
    #thymeleaf模板引擎
  thymeleaf:
    #是否开启缓存，建议开发时关闭，部署时开启
    cache: true
    #检测模板是否存在
    check-template: true
    #检测模板位置是否存在
    check-template-location: true
    #模板文件编码
    encoding: utf-8
    #模板文件位置
    prefix: classpath:/static/
    #content-type配置
    servlet:
      content-type: text/html
    #模板文件后缀
    suffix: .html

#mybatis配置
mybatis-plus:
  mapper-locations: classpath:mapper/**/*.xml,classpath:mapper/*.xml
  #MyBaits 别名包扫描路径，开启后在 Mapper 对应的 XML 文件中可以直接使用类名，而不用使用全限定的类名，多个package用逗号或者分号分隔
  typeAliasesPackage: com.crcm.auth.entity
  global-config:
    #主键类型  0:"数据库ID自增", 1:"用户输入ID",2:"全局唯一ID (数字类型唯一ID)", 3:"全局唯一ID UUID";
    id-type: 0
    #字段策略 0:"忽略判断",1:"非 NULL 判断"),2:"非空判断"
    field-strategy: 2
    #驼峰下划线转换
    db-column-underline: true
    #刷新mapper 调试神器
    refresh-mapper: true
    #是否开启大写命名，默认不开启
    capital-mode: true
    #逻辑删除配置
    #逻辑已删除值,(逻辑删除下有效)
    logic-delete-value: 1
    #逻辑未删除值,(逻辑删除下有效)
    logic-not-delete-value: 0
  configuration:
    #驼峰命名
    map-underscore-to-camel-case: true
    #mybatis二级缓存
    cache-enabled: false
    #打印执行的sql，开发时候用
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    #配置JdbcTypeForNull, oracle数据库必须配置
    jdbc-type-for-null: 'null'
    #MyBatis 自动映射时未知列或未知属性处理策略 NONE：不做任何处理 (默认值), WARNING：以日志的形式打印相关警告信息, FAILING：当作映射失败处理，并抛出异常和详细信息
    auto-mapping-unknown-column-behavior: warning

# 代码生成
gen:
  # 作者
  author: guozhilin
  # 默认生成包路径 system 需改成自己的模块名称 如 system monitor tool
  packageName: com.sjz.governance
  # 自动去除表前缀，默认是true
  autoRemovePre: true
  # 表前缀（生成类名不会包含表前缀，多个用逗号分隔）
  tablePrefix: t_,tbl_,pp_wxfw_,pp_ybgygf_,ct_
  # baseEntity公共字段，不会被生成
  publicColumn: create_time,create_by,update_time,update_by
  baseController: com.crcm.core.base.BaseController
  baseEntity: com.crcm.cloud.start.data.mybatis.bean.BaseEntity
  resultClass: com.crcm.core.response.RestResult


security:
  ignored:
    urls:
      - /**
      - /index
      - /sockjs-node/info
      - /login
      - /socket/**
      - /druid/**
      - /csrf
      - /webjars/springfox-swagger-ui/**
      - /resources/**
      - /static/**
      - /**.css
      - /**.js
      - /images/**
      - /lib/**
      - /api/*.json
      - /test/**
      #swagger
      - /swagger-resources/**
      - /swagger/**
      - /**/v2/**
      - /webjars/**
      - /**/doc.html
      # swagger2资源存放位置
      - /META-INF/resources/**
      # 对外开放api
      - /monitor/**