version: '3.8'
services:
  gateway:
    container_name: cloud-gateway
    image: 183.66.214.218:10800/test/cloud-gateway:latest
    privileged: true
    ports:
      - "8850:8850"
    environment:
      - TZ=Asia/Shanghai
      - NACOS_HOST=cloud-nacos
      - NACOS_PORT=8848
      - JAVA_OPTS=-XX:MetaspaceSize=128m -XX:MaxMetaspaceSize=128m -Xms1024m -Xmx1024m -Xmn256m -Xss256k -XX:SurvivorRatio=8 -XX:+UseConcMarkSweepGC
    restart: always
    depends_on:
      - admin
    networks:
      - cloud-net

  auth:
    container_name: cloud-auth
    image: 183.66.214.218:10800/test/cloud-auth:latest
    ports:
      - "8868:8868"
    environment:
      - TZ=Asia/Shanghai
      - NACOS_HOST=cloud-nacos
      - NACOS_PORT=8848
      - JAVA_OPTS=-XX:MetaspaceSize=128m -XX:MaxMetaspaceSize=128m -Xms1024m -Xmx1024m -Xmn256m -Xss256k -XX:SurvivorRatio=8 -XX:+UseConcMarkSweepGC
    depends_on:
      - admin
    networks:
      - cloud-net

  admin:
    container_name: cloud-admin
    image: 183.66.214.218:10800/test/cloud-admin:latest
    ports:
      - "8898:8898"
    environment:
      - TZ=Asia/Shanghai
      - NACOS_HOST=cloud-nacos
      - NACOS_PORT=8848
      - JAVA_OPTS=-XX:MetaspaceSize=128m -XX:MaxMetaspaceSize=128m -Xms1024m -Xmx1024m -Xmn256m -Xss256k -XX:SurvivorRatio=8 -XX:+UseConcMarkSweepGC
    networks:
      - cloud-net

  file:
    container_name: cloud-file
    image: 183.66.214.218:10800/test/cloud-file:latest
    ports:
      - "8920:8920"
    environment:
      - TZ=Asia/Shanghai
      - NACOS_HOST=cloud-nacos
      - NACOS_PORT=8848
      - JAVA_OPTS=-XX:MetaspaceSize=128m -XX:MaxMetaspaceSize=128m -Xms1024m -Xmx1024m -Xmn256m -Xss256k -XX:SurvivorRatio=8 -XX:+UseConcMarkSweepGC
    networks:
      - cloud-net

  monitor:
    container_name: cloud-monitor
    image: 183.66.214.218:10800/test/cloud-monitor:latest
    ports:
      - "8899:8899"
    environment:
      - TZ=Asia/Shanghai
      - NACOS_HOST=cloud-nacos
      - NACOS_PORT=8848
      - JAVA_OPTS=-XX:MetaspaceSize=128m -XX:MaxMetaspaceSize=128m -Xms1024m -Xmx1024m -Xmn256m -Xss256k -XX:SurvivorRatio=8 -XX:+UseConcMarkSweepGC
    networks:
      - cloud-net

  xxl-job:
    container_name: cloud-xxl-job
    image: 183.66.214.218:10800/test/xxl-job-admin:latest
    ports:
      - "8222:8222"
    environment:
      - TZ=Asia/Shanghai
      - NACOS_HOST=cloud-nacos
      - NACOS_PORT=8848
      - JAVA_OPTS=-XX:MetaspaceSize=128m -XX:MaxMetaspaceSize=128m -Xms1024m -Xmx1024m -Xmn256m -Xss256k -XX:SurvivorRatio=8 -XX:+UseConcMarkSweepGC
    networks:
      - cloud-net

# 使用创建环境时配置的网络
networks:
  cloud-net:
    external: true
    name: crcm-cloud-net